In [37]:
# import pandas as pd
import numpy as np
from database.query import DataAccess
from transformers import *
import pickle
from sklearn.externals import joblib

In [23]:
tweets_df = DataAccess.get_as_dataframe()
#tweets_df = DataAccess.sample_control(lower=0.0, upper=0.01)
print(len(tweets_df))
tweets_df.head()

72607

,created_at,lang,retweeted,text,place.full_name,place.country,entities.hashtags,user.created_at,user.favourites_count,user.followers_count,user.friends_count,user.statuses_count,user.verified,latitude,longitude
_id,,,,,,,,,,,,,,,
5ad7c4b9603fa924356751b6,Wed Apr 18 22:20:41 +0000 2018,fr,False,@LizzyMtl je te promet que je ne me prive de rien,"Baie-James, QuÃ©bec",Canada,[],Sat Mar 01 21:31:58 +0000 2014,94759,1496,2702,14773,False,NaN,NaN
5ad7c4ba603fa924356751b7,Wed Apr 18 22:20:42 +0000 2018,en,False,@tuinpeaks RIGHT the romance isn't even the ma...,"Mississauga, Ontario",Canada,[],Sat Dec 03 13:57:25 +0000 2016,3561,815,134,1389,False,NaN,NaN
5ad7c4ba603fa924356751b8,Wed Apr 18 22:20:42 +0000 2018,und,False,@sarahblyth Yay!!,"Vancouver, British Columbia",Canada,[],Tue Oct 27 18:48:54 +0000 2009,16735,1667,5000,7830,False,NaN,NaN
5ad7c4ba603fa924356751b9,Wed Apr 18 22:20:42 +0000 2018,en,False,"@cardiacclone32 Just say ""I had a good poop to...","Calgary, Alberta",Canada,[],Mon Jan 08 01:58:01 +0000 2018,381,43,68,560,False,NaN,NaN
5ad7c4bb603fa924356751ba,Wed Apr 18 22:20:42 +0000 2018,en,False,!!!!! Like wtf ðŸ˜­ https://t.co/4Y1mKCv6nE,"Toronto, Ontario",Canada,[],Wed Feb 08 06:53:46 +0000 2012,12334,1412,867,45042,False,NaN,NaN

In [32]:
cleaner = TextCleanExtractor()

tweets_df['clean_text'] = cleaner.transform(tweets_df.text)

In [33]:
tweets_df.head()

,created_at,lang,retweeted,text,place.full_name,place.country,entities.hashtags,user.created_at,user.favourites_count,user.followers_count,user.friends_count,user.statuses_count,user.verified,latitude,longitude,clean_text
_id,,,,,,,,,,,,,,,,
5ad7c4b9603fa924356751b6,Wed Apr 18 22:20:41 +0000 2018,fr,False,@LizzyMtl je te promet que je ne me prive de rien,"Baie-James, QuÃ©bec",Canada,[],Sat Mar 01 21:31:58 +0000 2014,94759,1496,2702,14773,False,NaN,NaN,je te promet que je ne me prive de rien
5ad7c4ba603fa924356751b7,Wed Apr 18 22:20:42 +0000 2018,en,False,@tuinpeaks RIGHT the romance isn't even the ma...,"Mississauga, Ontario",Canada,[],Sat Dec 03 13:57:25 +0000 2016,3561,815,134,1389,False,NaN,NaN,right the romance isn't even the main plot ( a...
5ad7c4ba603fa924356751b8,Wed Apr 18 22:20:42 +0000 2018,und,False,@sarahblyth Yay!!,"Vancouver, British Columbia",Canada,[],Tue Oct 27 18:48:54 +0000 2009,16735,1667,5000,7830,False,NaN,NaN,yay ! !
5ad7c4ba603fa924356751b9,Wed Apr 18 22:20:42 +0000 2018,en,False,"@cardiacclone32 Just say ""I had a good poop to...","Calgary, Alberta",Canada,[],Mon Jan 08 01:58:01 +0000 2018,381,43,68,560,False,NaN,NaN,"just say "" i had a good poop today "" thats pos..."
5ad7c4bb603fa924356751ba,Wed Apr 18 22:20:42 +0000 2018,en,False,!!!!! Like wtf ðŸ˜­ https://t.co/4Y1mKCv6nE,"Toronto, Ontario",Canada,[],Wed Feb 08 06:53:46 +0000 2012,12334,1412,867,45042,False,NaN,NaN,! ! ! like wtf ðŸ˜­

In [9]:
pa_tweets = df.physical_activity == 1
sb_tweets = df.sedentary_behavior == 1
sleep_tweets = df.sleep == 1

tweets = df.loc[pa_tweets | sb_tweets | sleep_tweets]

In [14]:
tweets.to_csv('./data/predicted_tweets.csv', index=False)